---
title: Links Úteis
url: {lib: libraries}
highlighter: prettify
hitheme: twitter-bootstrap
framework: purus
mode: selfcontained
--- 

---

## Livros, artigos e links sobre R
- [Livro Advanced R](http://adv-r.had.co.nz/). Livro que contém informações extremamente precisas sobre o R.
- [Tidy data](http://www.jstatsoft.org/v59/i10/paper). Artigo que explica a filosofia Tidy Data.
- [Site do shiny](http://shiny.rstudio.com). Sobre o fantástico Shiny.
- [R-bloggers](http://www.r-bloggers.com/). Um aglutinador de blogs sobre R.
- [R Cookbook (tutoriais rápidos)](http://www.cookbook-r.com/). Tutoriais fáceis e rápidos sobre R. Alguns estão desatualizados.
- [An Introduction to Statistical Learning with applications in R](http://www-bcf.usc.edu/~gareth/ISL/ISLR%20First%20Printing.pdf). Aplicação de diversas técnicas estatísticas em R, incluindo modelos lineares, reamostragem e machine learning.
- [Documentação do ggplot2](http://ggplot2.org/). Página de documentação do pacote `ggplot2`.
- [Tutorial básico do dplyr](http://cran.rstudio.com/web/packages/dplyr/vignettes/introduction.html). Introdução ao pacote `dplyr`
- [Livro R inferno](http://www.burns-stat.com/pages/Tutor/R_inferno.pdf). Uma abordagem divertida sobre conceitos de R.
- [Criação de pacotes do R](http://r-pkgs.had.co.nz/description.html). Guia para criação de pacotes no R.
- [Guia do R Markdown](http://rmarkdown.rstudio.com/). Guia para utilização do R markdown.
- [Site do knitr](http://yihui.name/knitr/). Informações sobre o fantástico pacote `knitr`.
- [Curso básico de R](https://www.codeschool.com/courses/try-r). Curso básico de R do Code School.
- [Shinyapps](http://www.shinyapps.io/). Sobre o ShinyApps.
- [The R Book](http://www.kharms.biology.lsu.edu/CrawleyMJ_TheRBook.pdf). Clássico livro de R, praticamente uma bíblia.
- [Modelos de Regressão](http://www.ime.usp.br/~giapaula/texto_2013.pdf). Livro que está sendo escrito pelo professor Gilberto sobre GLM e GEE, com aplicações em R.
- [Métodos computacionais em inferência estatística](http://www.leg.ufpr.br/lib/exe/fetch.php/pessoais:mcie-sinape-v12.pdf). Livro que trata de aspectos computacionais, eficiência de código, entre outros. E é em português.

## Outros links úteis
- [Como criar questões no stack overflow](http://pt.stackoverflow.com/editing-help).
- [Melhores práticas para postar no stack overflow](http://stackoverflow.com/help/how-to-ask).
- [Guia para utilização do github](http://rogerdudler.github.io/git-guide/index.pt_BR.html). Aprenda a utilizar o github em 5 minutos!
- [Sobre Markdown](http://daringfireball.net/). Sobre markdown em geral.
- [Sobre pandoc](http://johnmacfarlane.net/pandoc/). Sobre o conversor de tudo `pandoc`.
- [Sobre ROpenSci](http://ropensci.org/). Para interessados em open science.
- [Kaggle!!!](http://www.kaggle.com/). Desafios de data science com bases de dados reais!
- [Biblioteca D3.js](http://d3js.org/). Fantástica biblioteca gráfica do javascript.

E use o google!
