---
title: Aula 03 - Laboratório I
date : 2015-01-23
--- 

## Relatórios dinâmicos com RMarkdown

- Utilização da linguagem de marcação _markdown_.
- Possibilidade de incluir código R nos arquivos.
- Roda com o pacote `knitr` e o programa `pandoc`.
- Possibilidade de criar relatórios em html, docx, pdf, latex, entre outros.
- Possibilidade de criar apresentações e relatórios com gráficos dinãmicos.
- Possibilidade de inserir sintaxe matemática, como $e^{i\pi}=-1$, nos documentos.
- Documentos interativos com o `shiny`.

---

### Como utilizar

- Mais fácil com RStudio.
- Conceitos básicos de Markdown [nesse link](http://daringfireball.net/projects/markdown/).
- RMarkdown com exemplos [nesse link](http://rmarkdown.rstudio.com/).
- Sobre os metadados em YAML [nesse link](http://rmarkdown.rstudio.com/html_document_format.html).

#### Exemplo: [código que gerou a aula 01](https://github.com/curso-r/curso-r.github.com/blob/master/posts/aula01.Rmd).

```{r eval=FALSE, results='hide', echo=FALSE}
# ### Gráficos dinâmicos

# - Somente para output em HTML.
# - É possível criar gráficos baseados em javascript e gerar documentos que funcionam "sozinhos".
# - Se exigir interação, o shiny é utilizado, e o documento precisa ficar em um servidor.
# - É possível utilizar o shiny server e o serviço shinyapps.io para publicar documentos interativos.
# 
# #### Exemplo: Apresentação no ioslides
# ---
```

## Exercício do Laboratório

A base de dados [pnud.xlsx](http://curso-r.github.io/assets/data/pnud.xlsx) foi construida pelo Programa das Nações Unidas para o Desenvolvimento e contém informações demográficas e socioeconômicas de cada município brasileiro nos anos de 1991, 2000 e 2010. Essas informações são baseadas nos censos e são utilizadas para o cálculo do IDH municipal. A base
original pode ser baixada [neste link](http://www.atlasbrasil.org.br/2013/pt/download/). A [versão utilizada no laboratório](http://curso-r.github.io/assets/data/pnud.xlsx) foi ligeiramente modificada para facilitar algumas atividades.

### [Download](http://curso-r.github.io/assets/data/pnud.xlsx)

O arquivo contém 4 planilhas. Vamos utilizar a planilha _siglas_, que contém a definição das variáveis,
e a planilha _mun_, que contém as informações demográficas e socioeconômicas por município 
brasileiro.

__Queremos que vocês descubram__:

- Quais são os seis municípios com os maiores IDH municipais em 2010.
- Qual é a unidade federativa com menor expectativa de vida média, ponderada pela população dos municípios em 2000.
- Quais são os municípios _outliers_ com relação ao índice de Gini em 1991 e em 2010. 

__Outras atividades__:

- Monte um gráfico que mostre no eixo `x` a quantidade de municípios (em forma de porcentagem) e no eixo `y` a população acumulada desses municípios. Ordene os dados de forma apropriada para responder a pergunta: 20% dos municípios concentram quantos % da população? E os 30%? E x% (crie uma função)?
- Categorize a renda per capita e associe com a expectativa de vida.
- Você acha que a situação do Brasil está melhorando? Justifique utlizando dados de pelo menos 3 variáveis.
- No nordeste o aumento de distribuição de renda foi maior do que no sudeste?
- Insira mais pelo menos 3 estudos que você ache interessante.

## Relatório

Elabore um relatório utilizando RMarkdown com uma análise descritiva da base de dados do PNUD, 
descrevendo as variáveis utilizadas e executando as atividades pedidas.
